### ISSUE TITLE
macOS x86_64 wheel for v7.0.0 is unavailable

### ISSUE THREAD

**Issue by andy-sweet** [pyapp-kit/psygnal#156]
* psygnal version: 7.0.0
* Python version: 3.9.16, 3.11.1
* Operating System: macOS x86_64 (Intel)

### Description

The macOS x86_64 wheel successfully builds on CI, but testing/using it fails: https://github.com/pyapp-kit/psygnal/actions/runs/3744717286/jobs/6358389969#step:3:191

and then it does not get uploaded.

I assume this is mostly independent of Python version (at least in terms of the ones supported by psygnal).

### What I Did

Coming here from napari/napari, since psygnal is a dependency and this also caused a similar failure on our CI on `main`: https://github.com/napari/napari/actions/runs/3744884949/jobs/6358740535#step:8:112

**Comment by tlambert03** [comment]
yeah, I already noticed that and deleted the macos wheels... you're still seeing it?

**Comment by tlambert03** [comment]
note that the release also includes a `psygnal-0.7.0-py3-none-any.whl` ... so there are arch-free wheels available too.  It _might_ just take a moment for CI to recognize that the macos wheel is gone.  (I ran similar tests on magicgui, and while they failed on mac immediately after the release, they appear to all be passing now). https://github.com/pyapp-kit/magicgui/actions/runs/3744861617

can you try again in 10 mins or so and let me know if you still see it?

**Comment by andy-sweet** [comment]
> can you try again in 10 mins or so and let me know if you still see it?

Will do!

**Comment by andy-sweet** [comment]
Think it's good now: https://github.com/napari/napari/actions/runs/3744884949/jobs/6359146232

Thanks for the quick follow-up!

**Comment by tlambert03** [comment]
great, thanks for letting me know!  Opened a new issue to track the fixing of the wheels: https://github.com/pyapp-kit/psygnal/issues/157
