### ISSUE TITLE
Problem with mypyc and PyInstaller

### ISSUE THREAD

**Issue by kasasxav** [pyapp-kit/psygnal#162]
* psygnal version: the one in napari
* Python version: 3.9
* Operating System: windows

### Description

I am trying to generate an executable file and psygnal is a dependency of it (through napari). It was working before but now I run this error when rying to run the executable:

"ModuleNotFoundError: No module named 'fa33d3e2c63a4523d3c5__mypyc"

I have looked into the code and it seems to be coming from the decorator of mypy in _evented_decorator.py import _group.py (https://github.com/pyapp-kit/psygnal/blob/df1f6f6397957a682634c59679f5a62a79b392c0/src/psygnal/_group.py#L43). 

I saw in [014a285056c5b86d22715cdfd7cc2274466d94c2 ](https://github.com/pyapp-kit/psygnal/commit/014a285056c5b86d22715cdfd7cc2274466d94c2) that you changed from cython to mypyc and I think this might explain why it was working before and not anymore.

### What I Did

```
pyinstaller --specpath . setup.py (in ImSwitch)

It compiles into the distribution but when double clicking it runs that error.
```

**Comment by tlambert03** [comment]
yeah, @Czaki also had difficulties running pyinstaller with mypyc's approach.  he might have insight here

**Comment by tlambert03** [comment]
(btw, I'll note that all of those compiled files are completely optional, so as a workaround, simply delete all the compiled (`.so`) files from the psygnal directory/subdirectories and you should be fine)

**Comment by kasasxav** [comment]
Thanks for the quick answer! Deleting files sounds like something easy and interesting, in case they are optional. I don't manage to find them though, do you mean in site-packages? or in the pyinstaller dist folder? (in neither I found :l)

**Comment by tlambert03** [comment]
> do you mean in site-packages? or in the pyinstaller dist folder? (in neither I found :l)

haven't used pyinstaller in a while, so I can't quite remember, but basically, the point is that you want to delete any compiled files (`.so` on linux, and not sure on windows) from within the psygnal directory, wherever pyinstaller would be looking to import it.  So, I'd assume that's the site-packages that pyinstaller imports from when it creates the frozen package.  (i think the dist folder would be too late).

btw, deleting those compiled files would have the same effect as installing with `pip install psygnal --no-binary psygnal` in the first place

**Comment by kasasxav** [comment]
I deleted that but it fails because there is an import from a button within magicgui that needs to import psygnal.
I tried commenting the decorator inside the _group class but then I run with this error:

  File "napari\viewer.py", line 65, in __init__
  File "napari\plugins\__init__.py", line 46, in _initialize_plugins
  File "npe2\manifest\schema.py", line 309, in from_distribution
  File "npe2\manifest\schema.py", line 529, in _from_dist
  File "npe2\manifest\schema.py", line 409, in _from_entrypoint
FileNotFoundError: Could not find file 'builtins.yaml' in module 'napari_builtins'

I am not sure if this is caused by commenting that or if I moved on to the next error?

**Comment by tlambert03** [comment]
> I deleted that but it fails because there is an import from a button within magicgui that needs to import psygnal.

yeah, deleting it definitely should _not_ make psygnal unimportable, so if that happened, something went wrong.  Can you show me the import error you got?  is it module not found?  or something else?  Everything in psygnal should still be availble...

the decorator, by the way, is not the problem.  It's a "do nothing" decorator that simply modifies how mypyc compiles the class, but if you remove the decorator, it won't prevent the package from being compiled.  

That error you got looks like you probably moved on to the next error, and indicates that the `yaml` file for napari's built in plugins didn't make it into the pyinstaller bundle (so, you might need to explicitly declare it as `datas`)

**Comment by Czaki** [comment]
@kasasxav here is my handle for psygnal and pyinstaller https://github.com/4DNucleome/PartSeg/blob/3449dc2eea339f1b4998e4c7c5ee6088aa4db9c9/launcher.spec#L93-L96

And here is my handle for yaml file: https://github.com/4DNucleome/PartSeg/blob/3449dc2eea339f1b4998e4c7c5ee6088aa4db9c9/launcher.spec#L142-L146

If you need some explanation or have other questions feel free to call me.

**Comment by tlambert03** [comment]
thank you @Czaki!

**Comment by kasasxav** [comment]
Hi @tlambert03, actually it seems that it did fix the error, the other error was related to the yaml file that @Czaki also mentioned. Thanks a lot! I actually just added a foldr with the yaml file and it worked.

**Comment by Czaki** [comment]
My `--pre` release tests for pyinstaller were not working properly so today I found that for new release of `psygnal` i need to add `"psygnal._dataclass_utils", "psygnal._weak_callback"` to `hiddenimports`

I put this comment here to help another user, I do not think it will require psygnal code update.

**Comment by tlambert03** [comment]
Thanks for the update @Czaki, for those curious: the list of compiled files that you may need to add to hidden imports can be found in pyproject.toml, in the `tool.hatch.build.targets.wheel.hooks.mypyc` section

**Comment by Czaki** [comment]
@tlambert03 Will you accept PR that will add pyinstaller entry points to psygnal?

See:
https://pyinstaller.org/en/stable/hooks.html#providing-pyinstaller-hooks-with-your-package

**Comment by tlambert03** [comment]
yep!
