### ISSUE TITLE
Setting derived properties in evented models causes duplicate events

### ISSUE THREAD

**Issue by andy-sweet** [pyapp-kit/psygnal#215]
* psygnal version: 0.9.1
* Python version: 3.9.6
* Operating System: macOS 13.4 (Intel)

### Description

Setting a derived property when using an evented model causes the associated event to be fired twice.

Coming from the same titled issue over on napari: https://github.com/napari/napari/issues/6032

Our solution (https://github.com/napari/napari/pull/6035) was to block the event in `__setattr__`, but would be curious if you had better ideas.

### What I Did

```
from psygnal import EventedModel

class Model(EventedModel):
    a: int

    @property
    def b(self) -> int:
        return self.a + 1

    @b.setter
    def b(self, b) -> None:
        self.a = b - 1

    class Config:
        allow_property_setters = True
        property_dependencies = {"b": ["a"]}

m = Model(a=0)
m.events.a.connect(lambda _: print('a'))
m.events.b.connect(lambda _: print('b'))
m.a = 1 # prints "a" and "b" once each, as expected
m.b = 3 # prints "a" once, but "b" twice
```

**Comment by tlambert03** [comment]
Thanks!  I appreciate the ping.  Will have a look

**Comment by tlambert03** [comment]
nope, no better ideas :)  thanks for the heads up
