### ISSUE TITLE
Testing psygnal with pytest-qt

### ISSUE THREAD

**Issue by jacopoabramo** [pyapp-kit/psygnal#319]
* psygnal version: 0.11.1
* Python version: 3.10
* Operating System: Windows

For a project I'm working on, I'm using psygnal as signaling mechanism within my application. I would like to run unit tests on some internal parts of my project to ensure everything works properly. Is it possible to use pytest-qt together with psygnal to run unit tests and ensure that signals are correctly emitted?

**Comment by jacopoabramo** [comment]
Just answered myself by checking the local unit tests and the answer seems yes. Closing.

**Comment by tlambert03** [comment]
Yep!  As you found, it works.  I'll also note the long standing #46 "todo"... but that hasn't been urgent for me since I too just use pytest-qt in most cases

**Comment by tlambert03** [comment]
Another test pattern for synchronous applications is to connect your signal to a Mock(), perform your action, and then use mock.assert_called...

**Comment by jacopoabramo** [comment]
> Another test pattern for synchronous applications is to connect your signal to a Mock(), perform your action, and then use mock.assert_called...

Do you have an example I can look at?

**Comment by tlambert03** [comment]
yeah, that pattern is used all throughout the tests in this repo, for example:

https://github.com/pyapp-kit/psygnal/blob/8f4d781a57c85755a26c169608305e5525cbec05/tests/test_psygnal.py#L109-L120


(note, it really doesn't need to be `MagicMock` there... a simple `Mock()` would also work fine)

**Comment by tlambert03** [comment]
yeah, one doesn't need to be using unittest as a test runner to take advantage of `patch` and `mock`.  Those are just generally useful objects regardless of your test runner
