### ISSUE TITLE
[Best Practice]: decorate Signal with websocket

### ISSUE THREAD

**Issue by beniroquai** [pyapp-kit/psygnal#326]
`General Question`

### Description

I'm not 100% sure if this isactually a good idea or even working. With ImSwitch we have a microscopy control software that can also be operated from remote. Right now evrythign is done through the fastapi REST-API, but I would like to have websockets for faster message transport - pretty much wherever I have a signal. This used to be a PyQT signal, but since @jacopoabramo pointed me to this beautiful framework, I switched to psygnal for the headless/no-qt version. This runs perfectly in a docker on a raspi with a react-app on top:  https://youseetoo.github.io/imswitch/index.html
The static API is available here: https://youseetoo.github.io/api/api.html

### Question

Is it possible to "decorate" every signal with a websocket so that a signal-trigger also sends a message over a websocket; Has anyone done it?

**Comment by tlambert03** [comment]
hey @beniroquai.  Sounds like a cool application.

I can provide some general thoughts/strategies, and if you point me to the exact python code with the emitter(s) that you want to monitor over a websocket, it might help clarify the best strategy.  (I don't see psygnal used in the source for that web-app, so perhaps you can guide me to it)

I think you probably have two options:

1. *globally* plug into emission of any and all events.  Right [here](https://github.com/pyapp-kit/psygnal/blob/019232e4b349c378d36e489d77fa4dc3386b95f9/src/psygnal/_signal.py#L1171-L1174) in the `emit` method of `SignalInstance`, there is a hook to essentially monitor any and all psygnal events. It's mostly used for debugging.  You install a hook (which is any function that accepts a single argument which is an instance of [`EmissionInfo`](https://psygnal.readthedocs.io/en/latest/API/?h=emissioninfo#psygnal.EmissionInfo)) by using the [`monitor_events`](https://psygnal.readthedocs.io/en/latest/API/utilities/?h=monito#psygnal.utils.monitor_events) context manager.  So, you could create a hook that converts the `EmissionInfo` into a websocket message.
    - one downside here is that psygnal itself is really only prepared to have a single "caller" of `monitor_events` (hence the context manager).  so if by some chance, anyone happened to use that public `monitor_events` context, it would temporarily override/replace your hook.
    - it also means that if you happen to be running in an environment with *any* other library that uses psygnal, you'll be hearing those signal as well. (it's global to all of psygnal)
1. Alternatively, you could create your own `SignalInstance` subclass and create your own little hook that only applies to any signal instance you made yourself (in ImSwitch or any other code you specifically want to emit over the websocket).  Here, you'd have full control.  It could look something like this:

```python
from typing import Any
import psygnal

class SignalInstance(psygnal.SignalInstance):
    def emit(
        self, *args: Any, check_nargs: bool = False, check_types: bool = False
    ) -> None:
        super().emit(*args, check_nargs=check_nargs, check_types=check_types)
        # add your custom websocket code here if you want to emit the signal to a
        # websocket AFTER the signal has been emitted to all python listeners

    def _run_emit_loop(self, args: tuple[Any, ...]) -> None:
        # add your custom websocket code here if you want to emit the signal to a
        # websocket BEFORE the signal has been emitted to all python listeners
        return super()._run_emit_loop(args)


# if you are using psygnal.Signal instead of directly using SignalInstance,
# you can create a subclass of Signal that uses your custom SignalInstance subclass:

class Signal(psygnal.Signal):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._signal_instance_class = SignalInstance
```

and then you'd have to replace every usage of `psygnal.SignalInstance` or `psygnal.Signal` with your custom version there (which could be relatively easy by swapping some imports)

----

- it's worth mentioning that it could be somewhat easy to get yourself into performance trouble here, so make sure your websocket code is very fast (or at least doesn't hold up the main thread too long)
- it's unclear to me how much the identity of the emitter matters to you (vs the contents of the emitted signal).  That's another consideration.  If you only have one main emitter bus in ImSwitch, perhaps that's no big deal.  But if not, then the `self` argument above in your custom SignalInstance would have knowledge the exact object onto which it had been installed.

hope that helps.

**Comment by beniroquai** [comment]
Hey @tlambert03 thanks a lot for the detailed explanation. I think this is exactly what I was looking for. The way ImSwitch creates the signal is by instantiating different frameworks (e.g. QT or No-QT). [Here](https://github.com/openUC2/ImSwitch/blob/master/imswitch/imcommon/framework/noqt.py#L23) you can find the no-qt implementation. So I would "simply" need to extend the Signal class if I understand that correctly. I think I would need to understand what this means for the rest of the code. Essentially I want to establish a feedback mechanism for e.g. position updates in the GUI without adding the websocket in all these places manually. The signal does it already anyway.
Since this is the only psygnal implementation used in our application, this should not really be an issue if I can listen to other psygnals as well ;-)

**Comment by beniroquai** [comment]
Ok..next challenge. What would be the smartest way to access something like a globally operating server from the newly derived Signal interface? Would I need to launch the websocket/fastapi inside the Signal or rather outside? I have started implementing your changes here https://github.com/openUC2/ImSwitch/blob/noqt-websocket/imswitch/imcommon/framework/noqt.py#L34. Most likely this is a far-away-psygnal-related question. So plesae ignore it if it feels completely out of scope. Thanks anyway!

**Comment by beniroquai** [comment]
Success! :D 
<img width="767" alt="image" src="https://github.com/user-attachments/assets/eaa1f6a9-db57-45fc-85b7-6b8f0727f1b4">

It's definitely not beautiful, but it works. I'm surprised. I have pushed the [changes](https://github.com/openUC2/ImSwitch/blob/67efd16da4d3ffb25f92b948710eb0d88fea17d3/imswitch/imcommon/framework/noqt.py) in case anyone ever needs something similar :)

**Comment by tlambert03** [comment]
awesome!  I was literally *just* preparing this comment. 

I played around with this a bit too (I'm a relative asyncio noob myself, so not at *all* sure about best practices there.  Your approach is much better than mine, but here's what I had hacked together demonstrating a couple principles as well...  The websocket manager in fastapi is clearly a good find)

```python
import asyncio
import random
from threading import Lock, Thread

import time
from typing import Any
from fastapi import FastAPI, WebSocket
from fastapi.responses import HTMLResponse
from psygnal import SignalInstance


app = FastAPI()
websocket_global = None
websocket_lock = Lock()
loop = asyncio.get_event_loop()


class SocketSignal(SignalInstance):
    def _run_emit_loop(self, args: tuple[Any, ...]) -> None:
        with websocket_lock:
            if websocket_global is not None:
                # Send message to the WebSocket
                asyncio.run_coroutine_threadsafe(
                    websocket_global.send_text(f"{args!r} from signal {self.name!r}"),
                    loop,
                )

        super()._run_emit_loop(args)


# a few signals
sig = SocketSignal((str,), name="test1")
sig2 = SocketSignal((int,), name="test2")


# some local thread that emits signals periodically
def run():
    while True:
        wait = random.randint(0, 10) / 4
        sig2.emit(wait)
        time.sleep(wait)


scope_thread = Thread(target=run)
scope_thread.start()

# ------------------- webapp -------------------

html = """
<!DOCTYPE html>
<html>
    <head>
        <title>WebSocket Example</title>
    </head>
    <body>
        <h1>WebSocket Example</h1>
        <form action="" onsubmit="sendMessage(event)">
            <input type="text" id="messageText" autocomplete="off"/>
            <button>Send</button>
        </form>
        <ul id="messages"></ul>
        <script>
            const ws = new WebSocket("ws://localhost:8000/ws");
            ws.onmessage = function(event) {
                const messages = document.getElementById('messages')
                const message = document.createElement('li')
                message.textContent = event.data
                messages.appendChild(message)
            };
            function sendMessage(event) {
                const input = document.getElementById("messageText")
                ws.send(input.value)
                input.value = ''
                event.preventDefault()
            }
        </script>
    </body>
</html>
"""


@app.get("/")
async def get():
    return HTMLResponse(html)


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    global websocket_global
    await websocket.accept()

    with websocket_lock:
        websocket_global = websocket

    try:
        # Keep listening for incoming messages (optional)
        while True:
            data = await websocket.receive_text()
            sig.emit(data)
            print(f"received msg: {data}")
    except Exception as e:
        print(f"Connection closed: {e}")
    finally:
        with websocket_lock:
            websocket_global = None
```

**Comment by beniroquai** [comment]
That looks clean! Thanks for sharing. How did you start this app? I'm not really sure about the uvicorn stuff. I think this won't be killed properly when I'm closing my app gracefully. Not ideal yet. Also the asyncio is very hacky in my case indeed. Making something sync that's async by nature is nahh...not beautiful - but it works! Real-time-position-updates ftw ;-)

Thanks a lot!!

**Comment by tlambert03** [comment]
a side comment or two:

- by [putting your code after `super().emit()`](https://github.com/openUC2/ImSwitch/blob/67efd16da4d3ffb25f92b948710eb0d88fea17d3/imswitch/imcommon/framework/noqt.py#L84) (as I had suggested), there is one downside and that is that you will always send a websocket message even if the signal is blocked or paused (see logic that causes early exit [here](https://github.com/pyapp-kit/psygnal/blob/019232e4b349c378d36e489d77fa4dc3386b95f9/src/psygnal/_signal.py#L1146-L1169)).  So you might indeed be better off extending `_run_emit_loop`  (which will only be called when callbacks are definitely being invoked) rather than `emit`. I know it's private, so let me know if you have concerns there.
- you've now fixed this in your branch that you linked above (which is great!) but [this pattern on main](https://github.com/openUC2/ImSwitch/blob/c8942de66852f17591de37a9354771253125b50e/imswitch/imcommon/framework/noqt.py#L23-L25) is error prone:
```python
class Signal(SignalInstance, abstract.Signal):
    ...

class Thread(abstract.Thread):    
    _started = Signal()
    _finished = Signal()

    def __init__(self):
        ...
```

specifically, it renames SignalInstance to Signal (which is fine if you want to :)) but then uses that directly as a class attribute (which is *not* fine).  if you want to go straight to the SignalInstance, you should definitely create `self._started = Signal()` inside of `__init__`, otherwise all instances will share the literal same signal (which is generally not what you want).   I recall in previous threads here, there was indeed a little confusion about how to use the descriptor `Signal` object in ImSwitch.  I didn't leave that conversation convinced that I had done a good job in educating/explaining ... so let me know if there are questions there.  In any case, it looks like you've moved back to `psygnal.Signal` in your branch... which is good.

**Comment by tlambert03** [comment]
> How did you start this app?

ah good point.  use `uvicorn file_name:app --reload` ... assuming you pasted my code above into `file_name.py`

**Comment by tlambert03** [comment]
that's a much better idea :joy:  @beniroquai do that instead :)

I remember considering that earlier on and for reasons I can't remember dismissed it.  But yeah, I totally agree

**Comment by beniroquai** [comment]
Got it. I'll give it a try! Thank you so much, both :)
