### ISSUE TITLE
Support for Union type hints

### ISSUE THREAD

**Issue by jacopoabramo** [pyapp-kit/psygnal#347]
* psygnal version: 0.11.1
* Python version: 3.10.16
* Operating System: Windows

### Description

I'm trying to describe a Signal that can emit an Union type, but mypy complains:

`Argument 1 to "Signal" has incompatible type "<typing special form>"; expected "type[Any] | Signature"`

But when emitting the signal the code runs normally. Furthermore, when using check_types_on_connect, it still executes fine.

### What I Did

```python
from psygnal import Signal
from typing import Union

class Emitter:
    sig = Signal(Union[int, str]) # type checker reports error "arg-type"

obj = Emitter()

def callback(value):
    print(value)

obj.sig.connect(callback)
obj.sig.emit(1)
obj.sig.emit("hello")
```

Any suggestion on how to make the type checker happy? Besides just ignoring the error

**Comment by tlambert03** [comment]
The object you're passing in there is _not_ a type hint.  It's an actual type (consistent with the Qt API that we were copying).  It needs to support isinstance.

However there's nothing at all wrong with using `Signal(object)` if you want to relax the bounds of what that object can be

**Comment by jacopoabramo** [comment]
> The object you're passing in there is not a type hint.

Well that's embarassing. Sorry for the silly question.

Anyway, thanks for the tip. Closing

**Comment by getzze** [comment]
I also got this error and found this issue. Since 3.10, UnionTypes are working with `isinstance`. Does it still makes sense to raise a Mypy error? Should UnionType be an allowed type for `Signal` arguments?

**Comment by jacopoabramo** [comment]
@getzze could you share a code snippet example?

**Comment by getzze** [comment]
```python
from typing import TypeAlias

from psygnal import Signal

signature: TypeAlias = str | None


class Test:

    value_changed = Signal(signature)

    value: signature

    def __init__(self, value: signature) -> None:
        self.value = value

    def set_value(self, value: signature) -> None:
        if not isinstance(value, signature):
            msg = f"value should be a {signature}"
            raise ValueError(msg)
        
        if value != self.value:
            self.value_changed.emit(value)
        self.value = value
```

Mypy output is:

```
test.py:6: error: Argument 1 to "Signal" has incompatible type "UnionType | type[str]"; expected "type[Any] | Signature"  [arg-type]
```

But this code runs without error in python 3.14 (and it should work the same in python 3.10)

**Comment by jacopoabramo** [comment]
Yes I tested in python 3.10 and runs with no error while mypy gives the same output.

I'm not sure how to address from the typing perspective honestly. But in general I realized that when you want to emit complex types it's acceptable to follow the original suggestion of using `object`. Then perform the type narrowing in the connected callback(s).

Maybe `str | None` could be supported via #304

**Comment by getzze** [comment]
Maybe adding `UnionType` as a valid type for `Signal` arguments would be sufficient.
